### ISSUE TITLE
initial_model loading error when using TPU

### ISSUE THREAD

**Issue by hovanesgasparian** [sayakpaul/Learnable-Image-Resizing#1]
When trying to load the initial_model, I get the following error:

`InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on initial_model/variables/variables: Unimplemented: File system scheme '[local]' not implemented (file: 'initial_model/variables/variables') [Op:Identity]`

**Comment by sayakpaul** [comment]
TPUs cannot load local data (barring a few exceptions). You need to host the `initial_model` on a GCS Bucket accessible by the TPU in order to make it work. 

I think it's mentioned in the notebook too.

**Comment by hovanesgasparian** [comment]
Oh my apologies and thank you for the prompt response!
